-- MUVESKILL BH · schema inicial para Supabase
-- Execute este arquivo no SQL Editor do seu projeto.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  type text not null default 'Viajante' check (type in ('Viajante', 'Hostel')),
  name text not null,
  handle text not null,
  role text not null default '',
  city text not null default 'Belo Horizonte',
  avatar text not null default '',
  cover text not null default '',
  bio text not null default '',
  tags jsonb not null default '[]'::jsonb,
  stats jsonb not null default '{"works":0,"exchanges":0}'::jsonb,
  about text not null default '',
  looking jsonb not null default '[]'::jsonb,
  facts jsonb not null default '[]'::jsonb,
  photos jsonb not null default '[]'::jsonb,
  highlights jsonb not null default '[]'::jsonb,
  experiences jsonb not null default '[]'::jsonb,
  whatsapp text not null default '',
  space jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop policy if exists "Public profiles" on public.profiles;
create policy "Public profiles"
on public.profiles for select
using (true);

drop policy if exists "Users create own profile" on public.profiles;
create policy "Users create own profile"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users delete own profile" on public.profiles;
create policy "Users delete own profile"
on public.profiles for delete to authenticated
using (auth.uid() = id);

-- Fotos públicas dos perfis. Cada usuário só pode escrever na própria pasta.
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "Public profile photos" on storage.objects;
create policy "Public profile photos"
on storage.objects for select
using (bucket_id = 'profile-photos');

drop policy if exists "Users upload own profile photos" on storage.objects;
create policy "Users upload own profile photos"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users update own profile photos" on storage.objects;
create policy "Users update own profile photos"
on storage.objects for update to authenticated
using (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users delete own profile photos" on storage.objects;
create policy "Users delete own profile photos"
on storage.objects for delete to authenticated
using (
  bucket_id = 'profile-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Estrutura pronta para a próxima etapa: oportunidades e candidaturas.
create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  host_id uuid not null references public.profiles(id) on delete cascade,
  host_name text not null default '',
  skill text not null default '',
  exchange_type text not null default 'Permuta',
  title text not null,
  reward text not null default '',
  deadline text not null default '',
  description text not null default '',
  image_url text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.missions enable row level security;

drop trigger if exists missions_set_updated_at on public.missions;
create trigger missions_set_updated_at
before update on public.missions
for each row execute function public.set_updated_at();

drop policy if exists "Public missions" on public.missions;
create policy "Public missions"
on public.missions for select
using (true);

drop policy if exists "Hosts create missions" on public.missions;
create policy "Hosts create missions"
on public.missions for insert to authenticated
with check (auth.uid() = host_id);

drop policy if exists "Hosts update missions" on public.missions;
create policy "Hosts update missions"
on public.missions for update to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);

drop policy if exists "Hosts delete missions" on public.missions;
create policy "Hosts delete missions"
on public.missions for delete to authenticated
using (auth.uid() = host_id);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  mission_id bigint not null references public.missions(id) on delete cascade,
  host_id uuid not null references public.profiles(id) on delete cascade,
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  start_date date,
  message text not null default '',
  status text not null default 'sent',
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;

drop policy if exists "Applicants create own applications" on public.applications;
create policy "Applicants create own applications"
on public.applications for insert to authenticated
with check (auth.uid() = applicant_id);

drop policy if exists "Participants read applications" on public.applications;
create policy "Participants read applications"
on public.applications for select to authenticated
using (auth.uid() = applicant_id or auth.uid() = host_id);

drop policy if exists "Hosts update application status" on public.applications;
create policy "Hosts update application status"
on public.applications for update to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);
